services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
  redis:
    image: redis:7-alpine

  api_server:
    build:
      context: .
      dockerfile: Dockerfile
      target: api_server
    deploy:
      replicas: 3
    env_file:
      - .env
    depends_on:
      - db
      - redis

  log_worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: log_worker
    deploy:
      replicas: 2
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx_load_balancer:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_server

volumes:
  postgres_data: