"""Create url and visit tables

Revision ID: c210e72b6a32
Revises:
Create Date: 2025-08-15 10:31:44.040950+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c210e72b6a32"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("original_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("short_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("visit_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_url_original_url"), "url", ["original_url"], unique=False)
    op.create_index(op.f("ix_url_short_code"), "url", ["short_code"], unique=True)
    op.create_table(
        "visit",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "visitor_ip", sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False
        ),
        sa.Column("url_id", sa.Integer(), nullable=False),
        sa.Column(
            "visited_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["url_id"],
            ["url.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("visit")
    op.drop_index(op.f("ix_url_short_code"), table_name="url")
    op.drop_index(op.f("ix_url_original_url"), table_name="url")
    op.drop_table("url")
    # ### end Alembic commands ###
